### ISSUE TITLE
add /tests to .gitignore ?

### ISSUE THREAD

**Issue by JoeMurray** [JMAConsulting/biz.jmaconsulting.lineitemedit#16]
Should we add the tests directory to .gitignore so it is not included in deployments, at least ones that are done via git.

**Comment by monishdeb** [comment]
@JoeMurray I am not sure, because if we add the entire tests/ directory in .gitignore then we will lose all the written UTs from this git repo. Also if we want to keep only the UT files under tests/phpunit/CRM/* and exclude other files then, then if someone wants to run the UTs might need to regenerate those excluded files via ```civix```. 

If I look at other extensions which got UTs like https://github.com/eileenmcnaughton/nz.co.fuzion.civitoken it didn't excluded the test/* directory

**Comment by JoeMurray** [comment]
See https://chat.civicrm.org/civicrm/pl/kqbthb7jrbno5nxduysswhrp6h

**Comment by monishdeb** [comment]
@JoeMurray I have resolved the problem by adding ```.gitattributes``` file. Thanks for raising this issue in the extension channel. Here's what I have done:
1. Added .gitattributes file in my lineitemedit extension - https://github.com/JMAConsulting/biz.jmaconsulting.lineitemedit/commit/d07c6bf8aa79454d425c1206dcccc82024186826
2. published a release 1.3

When I downloaded the ext zip https://github.com/JMAConsulting/biz.jmaconsulting.lineitemedit/archive/1.3.zip , after extraction the ext directory doesn't retain those listed files
