### ISSUE TITLE
Broken Batch Validation

### ISSUE THREAD

**Issue by clement888** [JMAConsulting/biz.jmaconsulting.lineitemedit#25]
Hello, 

We had a CIVICRM instance (CiviCRM 4.7.29 on Wordpress 4.9.8 on Ubuntu) running well and doing batch validation under CiviContribution well but had recently choked on validation with the following error:

** text version of the error at the end of this post batch validation error

The change that seem to have taken place before this is the installation of the Edit Line Item (v2.0) extensions.  

We also saw a possibly related error complains of "Invalid Price fields: the following Price Set Fields use disabled or invalid financial types and need to be fixed if they are to still be used." at the CIVICRM dashboard.  It lists the following:

Price Set                      Price Set Field                Action Link
Contribution Amount | Additional Line Item 1 | View Price Set Fields

There would he Additional Line Item 1 to Addiational Line Item 10

Would anyone be able to advise how we can regain the batch validation function. We have uninstalled the above extension but the problem still persists.

Thanks in advance!

===========

Text of error message

CRM_Core_Exception: expected only one price field to be in price set but multiple are present in /var/www/html/wp-content/plugins/civicrm/civicrm/CRM/Batch/Form/Entry.php on line 453 Exception trace

Function Location
0 CRM_Price_BAO_PriceSet::getOnlyPriceFieldID(Array) /var/www/html/wp-content/plugins/civicrm/civicrm/CRM/Batch/Form/Entry.php:453 1 CRM_Batch_Form_Entry->processContribution(Array) /var/www/html/wp-content/plugins/civicrm/civicrm/CRM/Batch/Form/Entry.php:418 2 CRM_Batch_Form_Entry->postProcess() /var/www/html/wp-content/plugins/civicrm/civicrm/CRM/Core/Form.php:447 3 CRM_Core_Form->mainProcess() /var/www/html/wp-content/plugins/civicrm/civicrm/CRM/Core/QuickForm/Action/Upload.php:169 4 CRM_Core_QuickForm_Action_Upload->realPerform(Object(CRM_Batch_Form_Entry), 'upload') /var/www/html/wp-content/plugins/civicrm/civicrm/CRM/Core/QuickForm/Action/Upload.php:136 5 CRM_Core_QuickForm_Action_Upload->perform(Object(CRM_Batch_Form_Entry), 'upload') /var/www/html/wp-content/plugins/civicrm/civicrm/packages/HTML/QuickForm/Controller.php:203 6 HTML_QuickForm_Controller->handle(Object(CRM_Batch_Form_Entry), 'upload') /var/www/html/wp-content/plugins/civicrm/civicrm/packages/HTML/QuickForm/Page.php:103 7 HTML_QuickForm_Page->handle('upload') /var/www/html/wp-content/plugins/civicrm/civicrm/CRM/Core/Controller.php:351 8 CRM_Core_Controller->run() /var/www/html/wp-content/plugins/civicrm/civicrm/CRM/Utils/Wrapper.php:113 9 CRM_Utils_Wrapper->run('CRM_Batch_Form_E…', null, Array) /var/www/html/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php:282 10 CRM_Core_Invoke::runItem(Array) /var/www/html/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php:84 11 CRM_Core_Invoke::_invoke(Array) /var/www/html/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php:52 12 CRM_Core_Invoke::invoke(Array) /var/www/html/wp-content/plugins/civicrm/civicrm.php:1218 13 CiviCRM_For_WordPress->invoke('') /var/www/html/wp-includes/class-wp-hook.php:286 14 WP_Hook->apply_filters('', Array) /var/www/html/wp-includes/class-wp-hook.php:310 15 WP_Hook->do_action(Array) /var/www/html/wp-includes/plugin.php:453 16 do_action('toplevel_page_Ci…') /var/www/html/wp-admin/admin.php:224 17 {main}
Sorry, due to an error, we are unable to fulfill your request at the moment. You may want to contact your administrator or service provider with more details about what action you were performing when this occurred. expected only one price field to be in price set but multiple are present Return to home page.

**Comment by monishdeb** [comment]
Thanks, @clement888 for reporting this critical issue as it prevents the batch entry feature of Civi from working properly. 

For those wanting to know more about the technical background, here's an overview.

The validation error is triggered by a core function [CRM_Price_BAO_PriceSet::getOnlyPriceFieldValueID(..)](https://github.com/civicrm/civicrm-core/blob/master/CRM/Price/BAO/PriceSet.php#L539) on contribution 'Batch entry' submission if it encounters a default QC(quick-config) price set ( used to create offline contributions) that has more than one price field linked to it. The problem is that on install of lineitem-editor 2.0, it creates 10 QC price-fields linked to this default price set. This is the reason why eventually that core function throws the error message upon submission and halts the process. That core function was introduced long ago by this PR https://github.com/civicrm/civicrm-core/pull/3426 to ensure that no incorrect line-items are entered during batch entry.

I have fixed this issue by disabling those 10 price-fields just before submission in order to by-pass the validation message, and renabling those 10 PFs after submission. This retains the [multiple-inline-line-item additions](https://github.com/JMAConsulting/biz.jmaconsulting.lineitemedit/wiki/Allow-Item(s)-to-be-added-where-not-currently-allowed) feature offered by the 2.0 version of the Line Item Edit extension. The reason we cannot just remove that core function as an alternative to this hackish approach is that it fixes https://issues.civicrm.org/jira/browse/CRM-14793. The upside of the current (bit hackish) fix about disabling-reenabling is that it doesn't lead to any unintended regression/behaviour. In addition I have made some improvements to handle those Price Fields on enable/disable/uninstall of lineitem editor.

I have submitted a PR https://github.com/JMAConsulting/biz.jmaconsulting.lineitemedit/pull/26 If you are a developer it would be great if you could apply this patch and test that it resolves your issue. If you aren't a developer and would like to be linked to instruction on how to apply a patch, please let us know.

Cheers,
Monish (and Joe)

**Comment by monishdeb** [comment]
ping @JoeMurray

**Comment by clement888** [comment]
Thanks!  I am not a developer so i appreciate your guidance on how to apply the patch.  Thanks.

**Comment by MegaphoneJon** [comment]
Hi @clement888 - I can help you apply the patch.  Can you please log in to https://chat.civicrm.org then send a message to me there?  My name is "junglebird" there.  I'm getting on a call in 15 minutes, but after that (30-45 minute) call I'll be free for about 6 hours to help you.

**Comment by monishdeb** [comment]
@clement888 sorry for the delay. Here are the steps to apply the patch if you got Linux/MacOS 
1. Open the terminal and execute this commands
```
$  cd <path to extension dir>
$ wget  https://github.com/JMAConsulting/biz.jmaconsulting.lineitemedit/pull/26.patch
$ patch -p1 < 26.patch
```
2. If you got lineitem-editor extension already installed then clear CiviCRM cache (Go to - CiviCRM >> Administer >> System Settings >> Cleanup caches and paths)
3. Or reinstall the line-item editor. 

That's it, you can test the Batch Entry form to ensure if it fixes the issue.

Feel free to ping me (alias @monish) or @MegaphoneJon in https://chat.civicrm.org if you need help!

**Comment by JoeMurray** [comment]
FWIW, we're reviewing the constraint mentioned by Monish above that led to the need for the workaround, and if possible @monishdeb will contact Eileen about removing it so this error doesn't come up.

**Comment by clement888** [comment]
Thanks for the patch!  I have applied it to our staging system and it works.  We will be patching it to our production and i will update here again.

I was wondering since the batch validation function was working well before we installed the extension, why did the problem persist after we uninstall it ?  Thanks.

**Comment by larssandergreen** [comment]
@monishdeb @JoeMurray We're experiencing what appears to be the same issue after installing and later uninstalling Line Item Edit 2.3. From the error message (which I've pasted the first bit of below), it appears that we're having the same issue with the 10 price fields mentioned above. Is it perhaps the case that these price fields are added by Line Item Edit and not removed on uninstall? Or perhaps that it didn't uninstall cleanly for us.

Are you able to advise how we can fix the issue? Can we permanently disable those price fields (how would that be done exactly)? Or should we try installing and uninstalling again?

$Fatal Error Details = array(3) { ["message"]=> string(73) "expected only one price field to be in price set but multiple are present" ["code"]=> NULL ["exception"]=> object(CRM_Core_Exception)#2525 (10) { ["errorData":"CRM_Core_Exception":private]=> array(1) { ["error_code"]=> int(0) } ["cause":protected]=> NULL ["_trace":"PEAR_Exception":private]=> NULL ["message":protected]=> string(73) "expected only one price field to be in price set but multiple are present" ["string":"Exception":private]=> string(0) "" ["code":protected]=> int(0) ["file":protected]=> string(66) "/var/www/html/sites/all/modules/civicrm/CRM/Price/BAO/PriceSet.php" ["line":protected]=> int(528) ["trace":"Exception":private]=> array(15) { [0]=> array(6) { ["file"]=> string(64) "/var/www/html/sites/all/modules/civicrm/CRM/Batch/Form/Entry.php" ["line"]=> int(474) ["function"]=> string(19) "getOnlyPriceFieldID" ["class"]=> string(22) "CRM_Price_BAO_PriceSet" ["type"]=> string(2) "::" ["args"]=> array(1) { [0]=> array(7) { ["fields"]=> array(8) { [1]=> array(13) { ["id"]=> string(1) "1" ["name"]=> string(19) "contribution_amount" ["label"]=> string(19) "Contribution Amount" ["html_type"]=> string(4) "Text" ["is_enter_qty"]=> string(1) "0" ["weight"]=> string(1) "1" ["is_display_amounts"]=> string(1) "1" ["options_per_line"]=> string(1) "1" ["is_active"]=> string(1) "1" ["visibility"]=> string(6) "public" ["visibility_id"]=> string(1) "1" ["is_required"]=> string(1) "1" ["options"]=> array(1) { [1]=> array(11) { ["id"]=> string(1) "1" ["price_field_id"]=> string(1) "1" ["name"]=> string(19) "contribution_amount" ["label"]=> string(19) "Contribution Amount" ["amount"]=> string(11) "1.000000000" ["weight"]=> string(1) "1" ["is_default"]=> string(1) "0" ["is_active"]=> string(1) "1" ["financial_type_id"]=> string(2) "18" ["non_deductible_amount"]=> string(4) "0.00" ["visibility_id"]=> string(1) "1" } } } [704]=> array(13) { ["id"]=> string(3) "704" ["name"]=> string(22) "additional_line_item_1" ["label"]=> string(22) "Additional Line Item 1" ["html_type"]=> string(4) "Text" ["is_enter_qty"]=> string(1) "0" ["weight"]=> string(1) "1" ["is_display_amounts"]=> string(1) "1" ["options_per_line"]=> string(1) "1" ["is_active"]=> string(1) "1" ["visibility"]=> string(6) "public" ["visibility_id"]=> string(1) "1" ["is_required"]=> string(1) "1" ["options"]=> array(0) { } } [705]=> array(13) { ["id"]=> string(3) "705" ["name"]=> string(22) "additional_line_item_2" ["label"]=> string(22) "Additional Line Item 2" ["html_type"]=> string(4) "Text" ["is_enter_qty"]=> string(1) "0" ["weight"]=> string(1) "1" ["is_display_amounts"]=> string(1) "1" ["options_per_line"]=> string(1) "1" ["is_active"]=> string(1) "1" ["visibility"]=> string(6) "public" ["visibility_id"]=> string(1) "1" ["is_required"]=> string(1) "1" ["options"]=> array(0) { } } [706]=> array(13) { ["id"]=> string(3) "706" ["name"]=> string(22) "additional_line_item_3" ["label"]=> string(22) "Additional Line Item 3" ["html_type"]=> string(4) "Text" ["is_enter_qty"]=> string(1) "0" ["weight"]=> string(1) "1" ["is_display_amounts"]=> string(1) "1" ["options_per_line"]=> string(1) "1" ["is_active"]=> string(1) "1" ["visibility"]=> string(6) "public" ["visibility_id"]=> string(1) "1" ["is_required"]=> string(1) "1" ["options"]=> array(0) { } } [707]=> array(13) { ["id"]=> string(3) "707" ["name"]=> string(22) "additional_line_item_4" ["label"]=> string(22) "Additional Line Item 4" ["html_type"]=> string(4) "Text" ["is_enter_qty"]=> string(1) "0" ["weight"]=> string(1) "1" ["is_display_amounts"]=> string(1) "1" ["options_per_line"]=> string(1) "1" ["is_active"]=> string(1) "1" ["visibility"]=> string(6) "public" ["visibility_id"]=> string(1) "1" ["is_required"]=> string(1) "1" ["options"]=> array(0) { } } [708]=> array(13) { ["id"]=> string(3) "708" ["name"]=> string(22) "additional_line_item_5" ["label"]=> string(22) "Additional Line Item 5" ["html_type"]=> string(4) "Text" ["is_enter_qty"]=> string(1) "0" ["weight"]=> string(1) "1" ["is_display_amounts"]=> string(1) "1" ["options_per_line"]=> string(1) "1" ["is_active"]=> string(1) "1" ["visibility"]=> string(6) "public" ["visibility_id"]=> string(1) "1" ["is_required"]=> string(1) "1" ["options"]=> array(0) { } } [709]=> array(13) { ["id"]=> string(3) "709" ["name"]=> string(22) "additional_line_item_6" ["label"]=> string(22) "Additional Line Item 6" ["html_type"]=> string(4) "Text" ["is_enter_qty"]=> string(1) "0" ["weight"]=> string(1) "1" ["is_display_amounts"]=> string(1) "1" ["options_per_line"]=> string(1) "1" ["is_active"]=> string(1) "1" ["visibility"]=> string(6) "public" ["visibility_id"]=> string(1) "1" ["is_required"]=> string(1) "1" ["options"]=> array(0) { } } [710]=> array(13) { ["id"]=> string(3) "710" ["name"]=> string(22) "additional_line_item_7" ["label"]=> string(22) "Additional Line Item 7" ["html_type"]=> string(4) "Text" ["is_enter_qty"]=> string(1) "0" ["weight"]=> string(1) "1" ["is_display_amounts"]=> string(1) "1" ["options_per_line"]=> string(1) "1" ["is_active"]=> string(1) "1" ["visibility"]=> string(6) "public" ["visibility_id"]=> string(1) "1" ["is_required"]=> string(1) "1" ["options"]=> array(0) { } } } ["extends"]=> string(1) "2" ["financial_type_id"]=> string(2) "18" ["help_pre"]=> NULL ["help_post"]=> NULL ["is_quick_config"]=> string(1) "1" ["min_amount"]=> string(1) "0" } } } [1]=> array(6) { ["file"]=> string(64) "/var/www/html/sites/all/modules/civicrm/CRM/Batch/Form/Entry.php" ["line"]=> int(428) ["function"]=> string(19) "processContribution" ["class"]=> string(20) "CRM_Batch_Form_Entry" ["type"]=> string(2) "->" ["args"]=> array(1) { [0]=> array(7) { ["qfKey"]=> string(69) "e9214c8f3c9745d6ffb50a355f132b1b0903606f3f6156a5251b38d18c97d105_2408" ["entryURL"]=> string(80) "https://secure.wildsight.ca/civicrm/batch/entry?action=add&amp;id=89&amp;reset=1" ["batch_id"]=> string(2) "89"

**Comment by monishdeb** [comment]
@larssandergreen  actually this issue has been fixed in LineItem Editor ver 2.1, can you please ensure that you have the latest version installed in your setup ? If not please upgrade to latest stable ver 2.3 (https://civicrm.org/extensions/line-item-editor you will find it here). This will fix the issue.

**Comment by larssandergreen** [comment]
@monishdeb We had 2.3 installed, but uninstalled it and then the issue started. So we currently don't have it installed, but are experiencing the issue.
We'd prefer not to install it again, but will do so if you believe installing again and uninstalling may help.

**Comment by monishdeb** [comment]
@larssandergreen hmm the issue is line-item editor adds quick-config price fields (which later allows us to add multiple line-items via backoffice contribtuion), and those price fields are creating issue on batch import because of core, that I explained [above](https://github.com/JMAConsulting/biz.jmaconsulting.lineitemedit/issues/25#issuecomment-442032473). Now we cannot delete these price fields because it might result into data loss, so we choose to disable it on disabling/uninstalling the extension. I find it strange that the issue still appears upon unistalling the ext, as I have wrritten code to disable those price-field on uninstall [here](https://github.com/JMAConsulting/biz.jmaconsulting.lineitemedit/pull/26/files#diff-3564d4a2e223d280924c83bc927a3cd5c297cd2f567074b00c3fc56459ff2784R17). I wasn't able to replicate the issue on my local machine.

But there is a workaround where you don't need to install the ext again, if you have access to DB or API explorer can you disable the priceFields under ```PriceSet.name =  'default_contribution_amount'``` ? 

For DB 
```
UPDATE civicrm_price_field pf 
INNER JOIN civicrm_price_set ps 
   ON ps.id = pf.price_field_id AND ps.name = 'default_contribution_amount' AND pf.name <> 'contribution_amount' SET pf.is_active=0;
```

or via API 
```php
civicrm_api3('PriceField', 'get', [
      'price_set_id' => 'default_contribution_amount',
       'name' => ['!=' => 'contribution_amount']
       'api.PriceField.create' => ['id' => "$value.id", 'is_active' => FALSE]
 ]);
 ```
 Thats it, that will fix the issue for you!

**Comment by larssandergreen** [comment]
Thanks @monishdeb. We replaced price_field_id with price_set_id in your SQL and changed 7 rows, which fixed the issue.

**Comment by JoeMurray** [comment]
@monishdeb , can you review the uninstall code to see if that might have been the issue for @larssandergreen ? Thanks.
