### ISSUE TITLE
Install fails with disabled financial types

### ISSUE THREAD

**Issue by larssandergreen** [JMAConsulting/biz.jmaconsulting.lineitemedit#58]
Attempting to install extension on 5.28.4 on Drupal with some financial types disabled results in a 503, no install and this message logged: Financial Type for Price Field Option is either disabled or does not exist.

Enabling all disabled financial types solves the issue, but it doesn't seem like that should be necessary.

**Comment by monishdeb** [comment]
@larssg-wildsight thanks for your report. Looking into it.

**Comment by monishdeb** [comment]
Steps I used, to replicate: 
1. Check which financial type is used in quick config price field 'Contribution Amount' from api-explorer. I found 'Donation'
2. Disable the financial type (Donation here)
3. Install the line-item editor 

Result: throw a fatal error: "Financial Type for Price Field Option is either disabled or does not exist"

@larssandergreen as per the error message it seems like the error occurred when it tries to create price fields under default_contribution_amount price-set [here](https://github.com/JMAConsulting/biz.jmaconsulting.lineitemedit/blob/master/CRM/Lineitemedit/Util.php#L986) during install (these price-fields are later used to record additional line-item), but the associated financial type linked with the price-set seems to be disabled. I think in order to prevent the issue here, we need to throw a error message and prevent the install with an error message: 

```
You need to enable the 'Donation' financial type which is a required by line-item editor to add new price-fields. These price-fields are later used to record additional line-items on backoffice contribution.
```

@JoeMurray please provide your feedback?

**Comment by monishdeb** [comment]
The Line Item Editor is moved to https://lab.civicrm.org/extensions/lineitemedit. The new issue link for this ticket is  https://lab.civicrm.org/extensions/lineitemedit/-/issues/58
