### ISSUE TITLE
Add ability to add line items to line item edit

### ISSUE THREAD

**Issue by eileenmcnaughton** [JMAConsulting/biz.jmaconsulting.lineitemedit#6]
Adding this here as a feature request because I think it should be logged - but I recognise it is non-trivial. Basically it would be good to be able to add additional line items within the form

**Comment by monishdeb** [comment]
There is already a request from a client, in this regard i.e. to extend the ability of this ext to support additional line-item create. I'll share the spec once I get the approval from the client.

**Comment by eileenmcnaughton** [comment]
nice

**Comment by adixon** [comment]
I'm seeing this ability, but it's a bit curious.
1. It only showed up after I created the first price set (it was a test site that had no prices sets created previously).
2. I can only add a new line item if the total contribution amount is less than the amount paid.
3. New line items are only available from the price set used for the field (a good thing I think, but not immediately obvious).

I'm not sure if these are intentional or (my suspicion) a side effect of some other logic buried in the existing code.

I am curious about your answer, since you can create line items and from my review of the code that ability has been in there for the past year.

**Comment by monishdeb** [comment]
@adixon let me answer each of your point:
> It only showed up after I created the first price set (it was a test site that had no prices sets created previously).

That's right, add line-item link got exposed only in one condition If there is a price-set and it has price-field options avaiable to choose for a new line-item. There is a rule I made for adding line-item of a contribution which is **you cannot add new line-item with a price field which is already linked to a existing line-item of same contribution**, reason why I am not allowing non-quick config line-item because then it will share the same non-quick config price field id in line-item. And Civi doesn't allow that because there is [unique key](https://github.com/civicrm/civicrm-core/blob/master/xml/schema/Price/LineItem.xml#L140) defined for line-item table that doesn't allow multiple items with same price field and price field value ID against same contribution ID. Let me cite with an example, suppose you created a contribution with price-field (checkbox) option A and not chosen B & C. Then on edit contribution form you will see a 'Add line item' link and clicking that link will show you B and C price options to choose. Suppose you already have 3 line-items for this contribution which is linked to these 3 price options respectively. Then it will no longer show the 'Add line item' link to as you have already used up all 3 price options. From here, if you decided to cancel line-item linked with price option B, then the add line-item link will showup again and this time on Add line-item form it will show B as the only price field avaialble to choose.


> 2. I can only add a new line item if the total contribution amount is less than the amount paid.

That's not correct. I have explained the scenario above when you can add a new line item.

> 3. New line items are only available from the price set used for the field (a good thing I think, but not immediately obvious).

Yes new line items can be created only for price set fields only, as explained above.

**Comment by adixon** [comment]
Thanks for the explanation, it makes sense. I played around editing some line items of a contribution and from a user experience it was fairly confusing to figure out when I could add a line item and when I couldn't, but i expect that most users will stick within the limitations, since they mostly correspond to sensible options.

So my other question is still: doesn't this mean you already have the ability to add line items? Or is this issue about enhancing that ability somehow?

**Comment by monishdeb** [comment]
It's more about the latter approach to enhance the ability to add multiple line-item somehow by providing unique price field value id. Let see how far I can go in this direction and devise a plan if there is a possibility :)

**Comment by monishdeb** [comment]
Submitted PR https://github.com/JMAConsulting/biz.jmaconsulting.lineitemedit/pull/20

**Comment by monishdeb** [comment]
@adixon @eileenmcnaughton I am closing this issue now as this has been handled on #20 Please check the screencast on PR comments, as per which it extend the ability of backoffice form to add inline line-items against contribution made with w/o quick-config price set. Will be publishing new release 2.0 with this new change.
